/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package microfinance;

/**
 *
 * @author Henz
 */
public class Loading extends javax.swing.JFrame {

    /**
     * Creates new form Loading
     */
    public Loading() {
        initComponents();
        progress.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pourcentage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 280, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Loading...");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 200, 20));

        pourcentage.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pourcentage.setForeground(new java.awt.Color(0, 108, 155));
        pourcentage.setText("0 %");
        getContentPane().add(pourcentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 50, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gifs/new.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 370));
        getContentPane().add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 180, -1));

        setSize(new java.awt.Dimension(500, 369));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       Loading load = new Loading();
        load.setVisible(true);
        
        try
        {
            for (int i = 1; i < 100; i++)
            {
                Thread.sleep(50);
                load.progress.setValue(i);
                 load.pourcentage.setText(i+" %");
                if(i==0)
                {
                   
                }
                else if(i==10)
                {
                    
                }
                else if(i==20)
                {
                   
                }
                else if(i==30)
                {
                    
                }
                else if(i==40)
                {
                   
                }
                else if(i==50)
                {
                    
                }
                else if(i==60)
                {
                   
                }
                else if(i==70)
                {
                  
                }
                else if(i==80)
                {
           
                }
                else if(i==90)
                {
                    
                }
                else if(i==95)
                {
                    
                }
                load.progress.setValue(i);
            }
        }
        catch (Exception e)
        { 
            System.err.println(e);
        }
        Login open = new Login();
        load.setVisible(false);
        open.setVisible(true);
        load.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel pourcentage;
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables
}
